/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prime.medical;

import java.awt.Color;

/**
 *
 * @author esteb
 */
public class Login extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form Inicio
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prime = new javax.swing.JLabel();
        medical = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        iniciar = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exit = new javax.swing.JPanel();
        text_x = new javax.swing.JLabel();
        userText = new javax.swing.JTextField();
        passText = new javax.swing.JPasswordField();
        textingresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 550));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prime.setForeground(new java.awt.Color(255, 255, 255));
        prime.setText("PRIME MEDICAL");
        getContentPane().add(prime, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 140, 60));

        medical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/prime.png"))); // NOI18N
        medical.setText("jLabel5");
        getContentPane().add(medical, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 220, 180));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Kimoby Is The New Blue.png"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 280, 610));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 60));

        iniciar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        iniciar.setText("INICIAR SESIÓN");
        getContentPane().add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usuario.setText("USUARIO");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        contraseña.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contraseña.setText("CONTRASEÑA");
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        text_x.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        text_x.setText("X");
        text_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        text_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                text_xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                text_xMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(text_x, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text_x, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 889, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 40));

        userText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        userText.setForeground(new java.awt.Color(204, 204, 204));
        userText.setText("Ingrese su nombre de usuario");
        userText.setBorder(null);
        userText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTextMousePressed(evt);
            }
        });
        userText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextActionPerformed(evt);
            }
        });
        getContentPane().add(userText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 490, 20));

        passText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passText.setForeground(new java.awt.Color(204, 204, 204));
        passText.setText("Ingrese su contraseña");
        passText.setBorder(null);
        passText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTextMousePressed(evt);
            }
        });
        getContentPane().add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 490, 20));

        textingresar.setBackground(new java.awt.Color(49, 50, 253));
        textingresar.setForeground(new java.awt.Color(255, 255, 255));
        textingresar.setText("INGRESAR");
        textingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textingresarMouseExited(evt);
            }
        });
        textingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textingresarActionPerformed(evt);
            }
        });
        getContentPane().add(textingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 140, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_xMouseClicked
        System.exit(0);
    }//GEN-LAST:event_text_xMouseClicked

    private void text_xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_xMouseEntered
        exit.setBackground(Color.red);
        text_x.setForeground(Color.white);
    }//GEN-LAST:event_text_xMouseEntered

    private void text_xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_xMouseExited
        exit.setBackground(Color.white);
        text_x.setForeground(Color.black);
    }//GEN-LAST:event_text_xMouseExited

    private void userTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextMousePressed
        userText.setText("");
        userText.setForeground(Color.black);
        passText.setText("******");
        passText.setForeground(Color.gray);
    }//GEN-LAST:event_userTextMousePressed

    private void passTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTextMousePressed
        userText.setText("Ingrese su nombre de usuario");
        userText.setForeground(Color.gray);
        passText.setText("");
        passText.setForeground(Color.black);
    }//GEN-LAST:event_passTextMousePressed

    private void textingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textingresarMouseEntered
        textingresar.setForeground(Color.black);
    }//GEN-LAST:event_textingresarMouseEntered

    private void textingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textingresarMouseExited
        textingresar.setForeground(Color.white);
    }//GEN-LAST:event_textingresarMouseExited

    private void textingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textingresarActionPerformed
        inventario cu = new inventario ();
        cu.setVisible (true);
        this.setVisible (false);
        cu.setSize (996,624);
        cu.setLocationRelativeTo (null);
        cu.setResizable(false);
    }//GEN-LAST:event_textingresarActionPerformed

    private void userTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                Inicio o = new Inicio();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseña;
    private javax.swing.JPanel exit;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel iniciar;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel medical;
    private javax.swing.JPasswordField passText;
    private javax.swing.JLabel prime;
    private javax.swing.JLabel text_x;
    private javax.swing.JButton textingresar;
    private javax.swing.JTextField userText;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
